sudo: required
dist: trusty
language: node_js
node_js:
  - "8.11.4"
addons:
  chrome: stable

branches:
  only:
  - master

before_script:
- "export DISPLAY=:99.0" 
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to star
- npm install -g angular-cli
- npm install


script:
- ng test --watch=false --source-map=false
 