sudo: required
dist: trusty
language: node_js
node_js:
  - "9"
branches:
  only:
  - master

before_script:
- npm install -g angular-cli

script:
- ng build
- ng test --watch=false --browsers=ChromeHeadless
 